import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/navigation/header.navigation";
import Hero from "../components/sections/hero.section";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yousef Medhat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
    </div>
  );
};

export default Home;
